[package]
authors = ["roblabla <unfiltered@roblab.la>"]
name = "libtransistor-sys"
version = "0.0.0"

[build-dependencies]
bindgen = "0.31.3"

[dependencies]
core = { path = "../libcore" }
libc = { path = "../rustc/libc_shim" }
